## Exercice 1.1

In [2]:
import numpy as np
a = np.arange(0,100,3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

## Exercice 1.2

In [2]:
#Multiplie a par son carré
b = a**2
#Multiplie par pi/2
b = b*(np.pi/2)
#Calcule le sinus des valeurs de b
b = np.sin(b)
b

array([ 0.00000000e+00,  1.00000000e+00, -2.20436424e-15,  1.00000000e+00,
       -8.81745695e-15,  1.00000000e+00, -4.11555602e-14,  1.00000000e+00,
       -3.52698278e-14,  1.00000000e+00, -7.64253880e-14,  1.00000000e+00,
       -1.64622241e-13,  1.00000000e+00, -1.86173549e-13,  1.00000000e+00,
       -1.41079311e-13,  1.00000000e+00, -4.84086880e-13,  1.00000000e+00,
       -3.05701552e-13,  1.00000000e+00, -6.06706795e-14,  1.00000000e+00,
       -6.58488964e-13,  1.00000000e+00, -1.18966170e-12,  1.00000000e+00,
       -7.44694194e-13,  1.00000000e+00, -1.14257584e-12,  1.00000000e+00,
       -5.64317245e-13,  1.00000000e+00])

### Exercice 1.3

In [3]:
maxMatB = np.max(b)
maxMatB

1.0

### Exercice 1.4
2 Solutions :

In [4]:
compteur = 0
for i in b:
    if(i == maxMatB):
        compteur += 1
compteur
        

17

In [5]:
nb_maxInB = sum(b== maxMatB)
nb_maxInB

17

### Exercice 2.1

In [17]:
notDiag = [[1,2,3],[4,5,6],[7,8,9]]
diag = [[1,0,0],[0,5,0],[0,0,9]]
diag_triang_sup = [[1,2,3],[0,5,6],[0,0,9]]

In [18]:
def est_diagonale(matrix):
    to_test = np.triu(np.tril(matrix))
    if(matrix== to_test).all():
        return True
    else:
        return False
    

In [19]:
print(est_diagonale(notDiag))
est_diagonale(diag)

False


True

### Exercice 2.2

In [20]:
def est_triangulaire_sup(matrix):
    to_test = np.triu(matrix)
    if(matrix == to_test).all():
        return True
    else:
        return False

In [24]:
print(est_triangulaire_sup(diag_triang_sup))
print(est_triangulaire_sup(diag))
print(est_triangulaire_sup(notDiag))

True
True
False


### Exercice 3.1

In [13]:
i = 0;
j = 0;
k = 0;
tableau = [] 
for k in range(8):
    tableau.append([0] * 8) 
for i in range(8):
    for j in range(8):
        if j == 7:
            tableau[i][j] = 1
        if i == 7:
            tableau[i][j] = 1
        if j == 0:
            tableau[i][j] = 1
print(tableau)

[[1, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 1], [1, 1, 1, 1, 1, 1, 1, 1]]


In [22]:
np.array([[1, 0, 0, 0, 0, 0, 0, 1],[1, 0, 0, 0, 0, 0, 0, 1],[1, 0, 0, 0, 0, 0, 0, 1],[1, 0, 0, 0, 0, 0, 0, 1],[1, 0, 0, 0, 0, 0, 0, 1],[1, 0, 0, 0, 0, 0, 0, 1],[1, 0, 0, 0, 0, 0, 0, 1],[1, 1, 1, 1, 1, 1, 1, 1]])

array([[1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [9]:
import time
nb = 0
start = time.time()
for i in range(1000000):
    nb = i + nb
print(nb)
elapsed = (time.time() - start)
print(elapsed)

49999995000000
1.2026829719543457


In [28]:
start = time.time()
pwet = np.arange(0,1000000000)
np.sum([pwet])
elapsed = (time.time() - start)
print(elapsed)

5.467503309249878


In [60]:
ex5 = np.random.rand(50,50)
max = 0
for i in range(49):
    for j in range(49):
        if max < ex5[j+1][i]-ex5[i][j]:
            max = ex5[i][j]
print(max)

0.8805721938957679


In [4]:
ex6 = np.random.rand(50,50)
test = 0;
for i in range(50):
    for j in range(50):
        if ex6[i][j] > 0.5:
            test = test + 1
            ex6[i][j] = 0
        else:
            ex6[i][j] = 1
print(test)
print(ex6)

1243
[[1. 0. 0. ... 1. 0. 0.]
 [1. 0. 1. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 1. 0.]
 ...
 [0. 1. 0. ... 0. 1. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]]


In [66]:
a= np.array([[1,2,1,1],[0,1,2,1],[1,0,1,2],[2,1,0,1]]) 
b=np.array([0,0,1,0])
x = np.linalg.solve(a, b)
print(x)



[-0.5  0.  -0.5  1. ]


In [ ]:
matricec = nptriu(matricec)